// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43Mlcpzt4LW7ECwga6qzS3-KJE_kq6vo',
    appId: '1:9514187896:web:ba14eecc2e939f2ce2418d',
    messagingSenderId: '9514187896',
    projectId: 'auth-tutorial-4e77c',
    authDomain: 'auth-tutorial-4e77c.firebaseapp.com',
    storageBucket: 'auth-tutorial-4e77c.appspot.com',
    measurementId: 'G-RRY7JB4V4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Zna2X9yndqYmxkptVbzKsJbshnWswn8',
    appId: '1:9514187896:android:d1f9aa73293f693ee2418d',
    messagingSenderId: '9514187896',
    projectId: 'auth-tutorial-4e77c',
    storageBucket: 'auth-tutorial-4e77c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Y8-3h_GsZ37SX0FMohk1UnCdBL2cpAg',
    appId: '1:9514187896:ios:68083759eb74c99ae2418d',
    messagingSenderId: '9514187896',
    projectId: 'auth-tutorial-4e77c',
    storageBucket: 'auth-tutorial-4e77c.appspot.com',
    iosClientId: '9514187896-6p9ne3ksbokggsggsgreqd660ro8vk7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Y8-3h_GsZ37SX0FMohk1UnCdBL2cpAg',
    appId: '1:9514187896:ios:123b3e6a04b9b904e2418d',
    messagingSenderId: '9514187896',
    projectId: 'auth-tutorial-4e77c',
    storageBucket: 'auth-tutorial-4e77c.appspot.com',
    iosClientId: '9514187896-fvop4uhl1qink6iaj9eot42asrtud0km.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
